LTO_ENABLE = yes
ENCODER_MAP_ENABLE = yes
VIA_ENABLE = no

# Reduce compiled size
MOUSEKEY_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no

AVR_USE_MINIMAL_PRINTF = yes

MUSIC_ENABLE = no
